#!/usr/bin/env python3
# Regenerate embedded_ui_qvm.h from a ui.qvm file.
# The image is stored zlib-deflated to keep the core binary small; the engine
# inflates it once at load time (zlib is already linked).
# Usage: python3 embedded_ui_qvm_gen.py path/to/ui.qvm > embedded_ui_qvm.h
import sys, zlib

def main():
    if len(sys.argv) != 2:
        sys.stderr.write("usage: %s path/to/ui.qvm > embedded_ui_qvm.h\n" % sys.argv[0])
        return 1
    raw = open(sys.argv[1], "rb").read()
    comp = zlib.compress(raw, 9)
    out = []
    out.append("/*")
    out.append(" * embedded_ui_qvm.h - baseq3 ui.qvm baked into the core (zlib-compressed).")
    out.append(" *")
    out.append(" * Stock-format (vq3) Quake III q3_ui bytecode with the \"Fullscreen:\" menu")
    out.append(" * item and the \"Voodoo\" GL Driver entry removed (a libretro core always")
    out.append(" * renders fullscreen and has no 3dfx path). Stored deflated to keep the core")
    out.append(" * binary small; vm.c inflates it once at load via zlib.")
    out.append(" *")
    out.append(" * Used when no loose baseq3/vm/ui.qvm is present in a writable game")
    out.append(" * directory; dropping such a file overrides this embedded copy.")
    out.append(" *")
    out.append(" * Generated by embedded_ui_qvm_gen.py (do not edit by hand).")
    out.append(" */")
    out.append("#ifndef EMBEDDED_UI_QVM_H__")
    out.append("#define EMBEDDED_UI_QVM_H__")
    out.append("")
    out.append("/* zlib-deflated ui.qvm */")
    out.append("static const unsigned char embedded_ui_qvm_z[] = {")
    line = ""
    for i, b in enumerate(comp):
        line += "%d," % b
        if (i & 31) == 31:
            out.append(line)
            line = ""
    if line:
        out.append(line)
    out.append("};")
    out.append("")
    out.append("static const unsigned int embedded_ui_qvm_z_len = %d;  /* compressed size */" % len(comp))
    out.append("static const unsigned int embedded_ui_qvm_len   = %d;  /* inflated size */" % len(raw))
    out.append("")
    out.append("#endif /* EMBEDDED_UI_QVM_H__ */")
    sys.stdout.write("\n".join(out) + "\n")
    return 0

if __name__ == "__main__":
    sys.exit(main())
