#!/usr/bin/env python3
# Regenerate embedded_ui_qvm.h from a ui.qvm file.
# Usage: python3 embedded_ui_qvm_gen.py path/to/ui.qvm > embedded_ui_qvm.h
import sys

def main():
    if len(sys.argv) != 2:
        sys.stderr.write("usage: %s path/to/ui.qvm > embedded_ui_qvm.h\n" % sys.argv[0])
        return 1
    data = open(sys.argv[1], "rb").read()
    out = []
    out.append("/*")
    out.append(" * embedded_ui_qvm.h - baseq3 ui.qvm baked into the core.")
    out.append(" *")
    out.append(" * This is the stock-format (vq3) Quake III q3_ui bytecode with the")
    out.append(" * \"Fullscreen:\" video menu item removed (the libretro core always renders")
    out.append(" * fullscreen into the frontend framebuffer). It is used when no loose")
    out.append(" * baseq3/vm/ui.qvm is present in a writable game directory; dropping such a")
    out.append(" * file overrides this embedded copy.")
    out.append(" *")
    out.append(" * Generated by embedded_ui_qvm_gen.py (do not edit by hand).")
    out.append(" */")
    out.append("#ifndef EMBEDDED_UI_QVM_H__")
    out.append("#define EMBEDDED_UI_QVM_H__")
    out.append("")
    out.append("static const unsigned char embedded_ui_qvm[] = {")
    line = ""
    for i, b in enumerate(data):
        line += "%d," % b
        if (i & 31) == 31:
            out.append(line)
            line = ""
    if line:
        out.append(line)
    out.append("};")
    out.append("")
    out.append("static const unsigned int embedded_ui_qvm_len = %d;" % len(data))
    out.append("")
    out.append("#endif /* EMBEDDED_UI_QVM_H__ */")
    sys.stdout.write("\n".join(out) + "\n")
    return 0

if __name__ == "__main__":
    sys.exit(main())
